name: Release Subgraph Mock

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: "The commit SHA to be released"
      version_number:
        description: "The version number which the given commit SHA will be published as"

jobs:
  release-subgraph-mock-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - uses: apollographql/release-tooling/release-dockerhub@c3f1e8e459a22e5dbd9ac6112f2125995bd890d8
      name: "Release to DockerHub"
      with:
        commit_sha: ${{ inputs.commit_sha }}
        image_name: "subgraph-mock"
        version_number: ${{ inputs.version_number }}
